Repository Bastion-BaaS/bastion-server, pull requests merged in 2022-03, with the labels that each got.

#3 Create default collections and organise env vars
  docker-compose.yaml
  requests/create_ccf.rest
  requests/create_collection.rest
  requests/create_file.rest
  requests/create_user.rest
  requests/delete_collection.rest
  requests/delete_user.rest
  requests/remove_ccf.rest
  requests/remove_files.rest
  requests/run_ccf.rest
  requests/update_user.rest
  src/app.js
  src/aws/s3.js
  src/bastionServer.js
  src/controllers/cloudCode.js
  src/controllers/collections.js
  src/controllers/db.js
  src/controllers/user.js
  src/db/index.js
  src/index.js
  src/models/CloudCodeFunction.js
  src/models/DefaultSchema.js
  src/models/File.js
  src/models/User.js
  src/models/mongoOperator.js
  src/routers/cloudCodeRouter.js
  src/routers/collectionsRouter.js
  src/routers/dbRouter.js
  src/routers/index.js
  src/routers/userRouter.js
  src/utils/config.js
  src/utils/routeGenerator.js
Labels: Ready to Merge

#4 Add request authorisation logic for client-sdk and admin-app
  docker-compose.yaml
  requests/get_all_ccf.rest
  requests/run_ccf.rest
  src/bastionServer.js
  src/routers/cloudCodeRouter.js
  src/routers/collectionsRouter.js
  src/routers/dbRouter.js
  src/routers/filesRouter.js
  src/routers/genericRouter.js
  src/routers/index.js
  src/routers/userAuthRouter.js
  src/routers/userRouter.js
  src/utils/authenticate.js
  src/utils/routeGenerator.js
Labels: Ready to Merge

#5 User authentication and sessions
  docker-compose.yaml
  package-lock.json
  package.json
  src/bastionServer.js
  src/controllers/userAuth.js
  src/db/index.js
  src/models/User.js
  src/utils/config.js
  src/utils/routeGenerator.js
  src/utils/userAuthentication.js
Labels: Changes Requested

#8 Build files and CCF controller actions
  docker-compose.yaml
  package-lock.json
  package.json
  src/aws/ccf.js
  src/aws/s3.js
  src/bastionServer.js
  src/controllers/cloudCode.js
  src/controllers/files.js
  src/db/index.js
  src/models/CloudCodeFunction.js
  src/models/DefaultSchema.js
  src/models/File.js
  src/routers/filesRouter.js
  src/routers/genericRouter.js
  src/routers/userRouter.js
  src/utils/authenticate.js
  src/utils/config.js
  src/utils/routeGenerator.js
Labels: Ready to Merge

#9 Fixes
  Dockerfile
  src/routers/index.js
  src/utils/routeGenerator.js
Labels: Ready to Merge

#10 Add seed data and generate in development
  src/bastionServer.js
  src/controllers/collections.js
  src/db/index.js
  src/db/seed.js
  src/models/User.js
  src/utils/userAuthentication.js
Labels: Ready to Merge

#11 add fetch all records functionality to collections controller
  src/controllers/collections.js
Labels: Needs Review

#13 Pull ccfName out of params instead of body
  src/controllers/cloudCode.js
Labels: Ready to Merge

#15 Added middleware for cors. Runs before any routes are hit.
  src/bastionServer.js
  src/routers/filesRouter.js
  src/utils/routeGenerator.js
Labels: Ready to Merge
